
name: Publish to PyPI
on:
  release:
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/tests.yml

  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install pypa/build
        run: pip install build
      - name: Build package
        run: python -m build --sdist --wheel --outdir dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
